### ISSUE TITLE
Custom add - social share

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/MailtoWebmails#11]
Allow custom add so people can add the non-popular ones themselves rather then requesting it for public release.

Share these custom add's socially for all add-on users via drop down or something creative.

**Comment by mildred** [comment]
For anyone looking for custom add, I found how to do it manually:

- Go to [the option page](chrome://mailtowebmails/content/options/prefs.html)

- Open the web console `Ctrl+Shift+K`

- Execute the following lines (customize the name and uriTemplate) Copy and paste one line after another :

        handler = Cc['@mozilla.org/uriloader/web-handler-app;1'	].createInstance(Ci.nsIWebHandlerApp);
        handler.name="...";
        handler.uriTemplate = "http://.../compose&to=%s"
        handlerInfo = myServices.eps.getProtocolHandlerInfo('mailto');
        handlerInfo.possibleApplicationHandlers.appendElement(handler, false);
        myServices.hs.store(handlerInfo);

**Comment by Noitidart** [comment]
Thanks for sharing @mildred here is some more informtation on it: [GitHubGIST :: Noitidart / _ff-addon-tutorial-CheckGetSetRemoveAddHandlerOfProtocol.md](https://gist.github.com/Noitidart/2faaac70c62bc13e7773)

**Comment by Noitidart** [comment]
Feature has complete landed in v2.0
