### ISSUE TITLE
Add Webservice Request: Comcast.net

### ISSUE THREAD

**Issue by taylorjwalker** [Noitidart/MailtoWebmails#13]
I was trying to install a webmail service from the options panel of MailtoWebesrvices but the one I was looking for was not found. I was looking for Comcast.net.

**Comment by Noitidart** [comment]
I'll look into it. :)

**Comment by Noitidart** [comment]
Hey @taylorjameswalker it took awhile for me to find the wildcard mail handler but I found it.

I released it here: https://github.com/Noitidart/MailtoWebmails/commit/1118c2d93026e6d458021e8ae65cb494c8820e9e

Download XPI and install. :)

**Comment by Noitidart** [comment]
@taylorjameswalker  i think i found it.

Please try this:

https://web.mail.comcast.net/zimbra/?app=mail&view=compose&to=rawr@gmail.com

does it open your comcast webmail compose page?

**Comment by Noitidart** [comment]
Also @taylorjameswalker  try this one too:

https://web.mail.comcast.net/zimbra/h/search?action=compose&to=xxx@yyy.zzz

**Comment by Noitidart** [comment]
This is an old link, i dont think it works, the one in previous comment is correct one. http://web.mail.comcast.net/zimbra/mail?view=compose&to=%s

**Comment by Noitidart** [comment]
Hi @taylorjameswalker  I added this and its available in v2 please check it out and verify if its ok so we can close this issue. :)
