### ISSUE TITLE
Add Webservice Request: login.microsoftonline.com

### ISSUE THREAD

**Issue by callmetaste** [Noitidart/MailtoWebmails#14]
I was trying to install a webmail service from the options panel of MailtoWebesrvices but the one I was looking for was not found. I was looking for Outlook for organizations __*login.microsoftonline.com*__.

**Comment by Noitidart** [comment]
I can't make an account at login.microsoftonline.com can you please send an email to your suppot team with this question:

>  Hi, I was not able to find a wildcard mailto url to "Compose New Email" page. Do you have a url like Gmail does: 'https://mail.google.com/mail/?extsrc=mailto&url=%s' for gmail? if I replace the %s with a email it opens the gmail compose new email page with the email pre-populated. If not can you please create and provide me with one. Thanks

**Comment by Noitidart** [comment]
Hey @callmetaste can you please help me find the URL, did you get a chance to email the support team?

**Comment by Noitidart** [comment]
Hey @callmetaste did you get a chance to email them asking for a link I would love to hook this up.

**Comment by Noitidart** [comment]
Hey @callmetaste  can you get the correct url please, this one will not work. The URL should look like: `https://mail.google.com/mail/?extsrc=mailto&url=****************`, the `******` is where the clicked on email address gets populated. So like when you click on a mail link of `mailto:blah@hotmail.com` it will navigate to `https://mail.google.com/mail/?extsrc=mailto&url=mailto:blah@hotmail.com`. :)

**Comment by callmetaste** [comment]
@Noitidart 
Sorry I never responded. The link is
`https://outlook.office.com/owa/?realm=organization.com&to=email&subject=subject&body=body&cc=cc`

**Comment by Noitidart** [comment]
Thanks you @callmetaste for that! 

Currently this is what it is:
`https://outlook.office365.com/owa/?realm=YOUR_DOMAIN_HERE&rru=compose&to=%s`

We have the extra `rru=compose` is this ok? Or should I remove it from there?

**Comment by callmetaste** [comment]
Oh strange. Didn't notice it changed the link when I copied it.

`https://outlook.office.com/owa/?realm=example.com&rru=compose&to={to}&subject={subject}&body={body}&cc={cc}`

The 'rru=compose' is necessary

**Comment by Noitidart** [comment]
Oh cool. Thanks again. I'll close this now that its working for all.

By any chance would you know the mailto url for hotmail/live.com - they changed it and the one we have isn't working anymore. :(

**Comment by callmetaste** [comment]
I'll try to make a pull for you. Just a heads up though, it's my first time doing do.

Pull is here.
c64166f74f141f460c63942218afdfce8d5b9fff
