### ISSUE TITLE
MailToWebmails not woking properly with Fastmail

### ISSUE THREAD

**Issue by mcglewis** [Noitidart/MailtoWebmails#18]
I just installed MTW and when I click on a mailto link, it places the entire link in the "TO:" box in Fastmail (see attached image). Am I doing something wrong?
![mtw image](https://cloud.githubusercontent.com/assets/10372126/5900632/4e85e63a-a539-11e4-8752-b35a2d8b412e.png)

**Comment by Noitidart** [comment]
Thanks for that report, no you're not doing anything wrong, I'll look into why this is happening.

**Comment by Noitidart** [comment]
Hi @mcglewis thanks for this report. i fixed it and uploaded a new version (v1.3) to AMO:

It takes a couple days to get approved but you can download from here right away:

https://addons.mozilla.org/en-US/firefox/addon/mailtowebmails/versions/

**Comment by mcglewis** [comment]
And it's working! Thanks for the fast response -- great job!

Matt L.

**Comment by Noitidart** [comment]
:) thanks to users like you who report :)
