### ISSUE TITLE
Add Webservice Request: gmx.net

### ISSUE THREAD

**Issue by Tom-0169** [Noitidart/MailtoWebmails#19]
I was trying to install a webmail service from the options panel of MailtoWebesrvices but the one I was looking for was not found. I was looking for gmx.net

**Comment by Noitidart** [comment]
Thanks Tom for your report @rolchar also requested GMX but we are having a hard time finding the wild card URL. Please read the topic heere: https://github.com/Noitidart/MailtoWebmails/issues/12

If you can help us get in touch with GMX support team to get a wildcard url that would be awesome!
