### ISSUE TITLE
Add Webservice Request: Google inbox

### ISSUE THREAD

**Issue by hughjonesd** [Noitidart/MailtoWebmails#20]
I was trying to install a webmail service from the options panel of MailtoWebesrvices but the one I was looking for was not found. I was looking for Google Inbox (inbox.google.com)

**Comment by Noitidart** [comment]
Thanks hughjonesd, can you please send me an invite so I can figure out the mailto handler. My email is noitidart@gmail.com

Thanks!

**Comment by Noitidart** [comment]
Actually it seems I need to download it to my phone first, very weird.

Do you know the mailto url? If you can figure it out I can hook this up real fast.

**Comment by hughjonesd** [comment]
Send me a gmail address and I'll get you an invite...!

**Comment by Noitidart** [comment]
Thanks @hughjonesd but I don't have a compatible cell phone to download the app to, soI won't be able to activate it. :( So silly fo them to force you to do it on a phone >_<

**Comment by Noitidart** [comment]
Hey there hugh were you able to get a link if you email their support this message the should get back to you with a link i can hook up:

>Hi, I was not able to find a wildcard mailto url to "Compose New Email" page. Do you have a url like Gmail does: 'https://mail.google.com/mail/?extsrc=mailto&url=%s' for gmail? if I replace the %s with a email it opens the gmail compose new email page with the email pre-populated. If not can you please create and provide me with one. Thanks

**Comment by NickolasLapp** [comment]
Bump Bump. I would also like support for this feature.

**Comment by hughjonesd** [comment]
I think nowadays inbox works on computers if you have a gmail account.

**Comment by Noitidart** [comment]
Thanks @hughjonesd Ill take a look :)

**Comment by Noitidart** [comment]
I cant seem to get into a google inbox. can anyone join me on irc and help me out?

https://chat.mibbit.com/?url=irc%3A%2F%2Fmoznet%2Fjsctypes my name is noida

**Comment by KingMob** [comment]
Seconded. Also, I sent you an invite, if that helps.

**Comment by Noitidart** [comment]
Thank you @KingMob this will help a ton I couldnt get in. Ill try now.

**Comment by Noitidart** [comment]
@KingMob I followed the invite, it said succesful. Now when I got to inbox.google.com its a blank page here is a screenshot:

![](http://i.imgur.com/okDtd6G.png)

Is anyone available to do a remote connect session?

**Comment by KingMob** [comment]
Apparently, installing it on a smartphone is mandatory. I can't do a remote connect, but I might be ableto give you a dummy account for testing this weekend.

**Comment by Noitidart** [comment]
Hey @KingMob  and all I got a device and tried installing but it's saying incompatible :(

![](http://i.imgur.com/n9PChz0.png)

Is anyone available and comfortable to allow me to remote connect to their computer? Or you can remote connect to mine, but i need to be in an account to sniff the headers.

Does google chrome have mailto handler for this? In which case I can just lift that url.

**Comment by Noitidart** [comment]
Apparently google chrome does, can anyone who has google chrome, or is comfortable with  installing it, can follow these steps to get me the mailto handler: http://webapps.stackexchange.com/a/24299

**Comment by Noitidart** [comment]
This is also another method to find the inbox handler on google chrome: https://productforums.google.com/d/msg/chrome/FngTaedzxWc/uCB_pvAxkNkJ

You will likely have to use the DOM Inspector of Google Chrome once getting to these pages to find the mailto protocol link. If you can't find it, if you're comfotable with me connecting to your computer via TeamViewer I can help you out.

**Comment by KingMob** [comment]
@Noitidart I checked the Chrome handlers section, and there's no entry for Inbox yet, just mail.google.com. Quick scan of the DOM for "mailto" didn't reveal anything helpful. Thx for looking at this, I'm sorry, I don't have more time to help.

**Comment by Noitidart** [comment]
Thanks @KingMob I think it wont show in Chrome till you go to Inbox and then you'll get a popup bar, then you have to click "addas mail handler" then it should show there :)

**Comment by KingMob** [comment]
I don't see any pop-ups to add as mail handler. It's possible Google hasn't
offered that yet, since Inbox is still beta. (Real beta, not Gmail "beta".)

**Comment by Noitidart** [comment]
Thanks so much for the fast reply, goodness this is weird. Can you please try going to settings of Inbox and look for something "make inbox my default", I think it should be there. I thought I read something about that on the net.

Worst case, is it possible you can make me a dummy account and send those details my way? I want to hook you guys up pret

**Comment by Noitidart** [comment]
@KingMob you may need to enable it in google like this: https://support.google.com/chrome/answer/1382847?hl=en

**Comment by Noitidart** [comment]
Oh we can also probably email their support team for help with this, is there a support button?

**Comment by Noitidart** [comment]
Oh interesting find: https://productforums.google.com/forum/#!topic/inbox/SMykZMC4bSI

It looks like we'll have to email support to get their help, does the inbox.google have a link for "support"?

**Comment by KingMob** [comment]
@noitidart, the link you sent is for the same thing in Chrome. There's no
listing yet for Inbox in the handlers. Also, Google is notorious for not
offering live support. Unless, you're a large customer, there's no way of
getting on the phone with them.

I'd set up the account for you, but they require phone activation and I
don't have a second phone... I think it's a bit short-sighted of G, but
whatever. If you want another invite to use, I left one for
inboxmailto@mailinator.com:
https://mailinator.com/inbox.jsp?to=inboxmailto#/#showmailpane

**Comment by Noitidart** [comment]
Drats, thanks @KingMob for that extra invite. Ill try to get someones cell phone to use for it.

I finished 80% the backend for the new MailtoWebmails share engine feature last night. So people can update as they please instantly (well it has to get admin approval), but for those that add the engine it is available to them personally pre-admin approve. After admin approve is visible to the rest of the users of MailtoWebmails. I'm hoping to have update out within week.

**Comment by KingMob** [comment]
Sorry I can't help more. Thanks for a great project, btw.

m

**Comment by Noitidart** [comment]
No problem thanks @KingMob I already started work on v2 :) Thanks for the motivation!

**Comment by Noitidart** [comment]
Until they land this feature you guys might like this addon: https://addons.mozilla.org/en-US/firefox/addon/inbox-notifier/

I think it lets you pop the compose new mail page straight from that toolbarbutton.

**Comment by Noitidart** [comment]
Hey all did they add something yet?


Can you test this

    https://inbox.google.com/%s

So if you paste to your browser:

     https://inbox.google.com/mailto:blah@blah.com

Does it populate the compose with `blah@blah.com`?

**Comment by NickolasLapp** [comment]
No luck with that. Tested on Google Chrome an Mozilla Firefox with Ubuntu 14.04 64bit.

**Comment by Noitidart** [comment]
Thanks @NickolasLapp  for the quick reply! And in depth testing. :)

**Comment by KingMob** [comment]
Just tested in Firefox on OS X, can confirm, not working. Man, Google is
really letting their services languish these days.

m

**Comment by Noitidart** [comment]
Thanks @KingMob for the test! :)

By the way v2.1 has been approved. So as soon as anyone figures it out, if you submit it, it will show up for everyone else. :) No need to rely on me :) But I'll be here just in case! :)

**Comment by jdelamater99** [comment]
I've made a little progress on this. 

Testing this URL, works. It loads Inbox, opens a compose panel, and populates the To field.
https://inbox.google.com/u/0/?mailto=&to=blah@blah.com

But, when I try putting in the wild card, it isn't capturing the To address. It loads Inbox, opens a compose panel, but does not populate the To field.
https://inbox.google.com/u/0/?mailto=&to=%s

**Comment by Noitidart** [comment]
@jdelamater99 wow fantastic work there. I can't test it but hopefully some others can.

The reason is likely because the standardized method for these URLs, is that the wildcard is replaced with `mailto:blah@blah.com`. Notice the `mailto:` prefix. So `https://inbox.google.com/u/0/?mailto=&to=%s` would turn to `https://inbox.google.com/u/0/?mailto=&to=mailto:blah@blah.com`

**Comment by jdelamater99** [comment]
@Noitidart That looks like exactly what is happening. When I use the link, it strips the parameters out of the URL, leaving only inbox.google.com/u/0/, which made it tricky to get, because you had to stop the page before it adjusted the URL, but I managed to get it, and here is the URL that's being passed.

https://inbox.google.com/u/0/?mailto=&to=mailto%3Adestinyghoststories%40gmail.com

**Comment by Noitidart** [comment]
Wow fantastic! Does that work? I just approved your submission so it will now show in public under the "Discover" section for everyone. :)

**Comment by jdelamater99** [comment]
Only partially. It doesn't populate the To field. The mailto: (mailto%3a) is interferring with the script on the page that validates the to address. Taking that out, it works. 

https://inbox.google.com/u/0/?mailto=&to=blah%40blahl.com

**Comment by Noitidart** [comment]
@jdelamater99  I'll look into hacking firefox so we can bypass the mailto: auto prefix-ing. It'll be tough though its a standardized thing. Last I tried this, a year ago, it was deep deep inside and I couldn't pull it off.

**Comment by jdelamater99** [comment]
Thanks @Noitidart. 

I wrote a GreaseMonkey script, to use in the interim. If anyone wants to use this until a permanent solution is found, here is the link.

https://gist.github.com/jdelamater99/b5f852780a0236ce1db4#file-googleinbox_removeurlmailto-user-js

**Comment by Noitidart** [comment]
Hey @jdelamater99 does this URL template below, strip the mailto?

    https://inbox.google.com/?view=cm&fs=1&tf=1&source=mailto&to=%s

**Comment by jdelamater99** [comment]
@Noitidart, unfortunately no, that didn't work. 

I have 3 invites to inbox. If you would like, I can send you one. Might make it easier for testing and troubleshooting.

**Comment by Noitidart** [comment]
Thanks @jdelamater99  I really appreciate it, but I don't have a device to test it on :(

**Comment by Noitidart** [comment]
Hey alil can you please try this URL: `https://inbox.google.com/mail/?extsrc=mailto&url=mailto:YOUR_EMAIL_HERE` and see if it worksplease

**Comment by Noitidart** [comment]
Special thanks to Frank for submitting a fix for this. It has now been updated. Super super thanks to Frank, he solved what we have been struggling with for months!

I have marked google inbox as a popular handler so it shows on the main page now.

**Comment by jdelamater99** [comment]
Sorry for the late response, I didn't get an email notification for the previous comment asking for retesting. 

But I'm really glad that a solution was found. What was the solution, if you don't mind me asking.

**Comment by Noitidart** [comment]
Hi @jdelamater99  here is a quote from Frank in the email he sent me:
> Hello again,
> 
> I just double checked and it seems like the solution is actually rather simple. Have a look at the current link for Google Inbox:
> 
> https://inbox.google.com/u/0/?mailto=&to=%s
> 
> This one doesn't work, as Google Inbox expects the mail address ONLY when it comes to the "to" parameter. However, it will accept a complete mailto link using the "mailto" parameter (surprise), just like this:
> 
> https://inbox.google.com/u/0/?mailto=%s
> 
> I just tested the change and it works perfectly, even accepting additional subjects etc. I'm not sure why nobody else reached out to you regarding this bug, but it should probably get fixed upstream.
