### ISSUE TITLE
Add Webservice Request: Inbox by Gmail.

### ISSUE THREAD

**Issue by iansan5653** [Noitidart/MailtoWebmails#30]
I was trying to install a webmail service from the options panel of MailtoWebesrvices but the one I was looking for was not found. I was looking for Inbox by Gmail.

**Comment by Noitidart** [comment]
Thanks @iansan5653  for the request. We actually have an ongoing topic here: https://github.com/Noitidart/MailtoWebmails/issues/20

It seems google has not provided such a link for "Inbox" service yet. But as soon as they do I'll add it in and it will be availble publically instantly in version 2. Version 2 of mailtowebmails is pending review right now.

**Comment by Noitidart** [comment]
Also until google does add a mailto link. you might find this addon useful: https://addons.mozilla.org/en-US/firefox/addon/inbox-notifier/
