### ISSUE TITLE
Add Webservice Request: Inbox by Gmail

### ISSUE THREAD

**Issue by ViKomprenas** [Noitidart/MailtoWebmails#31]
I was trying to install a webmail service from the options panel of MailtoWebmail but the one I was looking for was not found. I was looking for [Inbox by Gmail](https://www.google.com/inbox/).
Also, is it possible in the future to add a generic one that simply opens whatever page you set up?

**Comment by ViKomprenas** [comment]
Whoops, just saw there's others requesting this.

**Comment by Noitidart** [comment]
Thanks man :)

**Comment by Noitidart** [comment]
Also for the generic one, yep, in version 2 its available, I released it, you can install it from the versions page, it hasnt got full review yet:

https://addons.mozilla.org/en-US/firefox/addon/mailtowebmails/versions/
