### ISSUE TITLE
Typo in default issue

### ISSUE THREAD

**Issue by ViKomprenas** [Noitidart/MailtoWebmails#32]
The default issue MailtoWebmails allows you to open calls the extension MailtoWebservices, and also misspells such in the issue body.

**Comment by Noitidart** [comment]
I don't understand can you please rephrase :)

I really appreciate you for getting onto github to get in touch with me :)

**Comment by ViKomprenas** [comment]
Doesn't occur in 2.0.

**Comment by Noitidart** [comment]
Thanks again very much for your feedback and help! :)
