### ISSUE TITLE
do you have malicious code on your website

### ISSUE THREAD

**Issue by soundfeelings** [Noitidart/MailtoWebmails#38]
I love your addon and wanted to use it again from my new computer. i added it to FIREFOX and then went to "options" which takes me to your website. Then my MALWAREBYTES warns me that you have malicious code on your site. maybe you are not aware of this or is it intentional. Anyway, i would love to continue using your addon but feel hesitant to do it until you clean this issue up. Can you please keep me posted? thank you.

**Comment by Noitidart** [comment]
Wow thanks very much for this report. May you please share that malware bytes report. There is no malicious code, the details being sent to the server are open source and visible right here - https://github.com/Noitidart/MailtoWebmails/blob/master/bootstrap.js#L509

And the contents of submitJson is seen in your local file here - https://github.com/Noitidart/MailtoWebmails/blob/master/bootstrap.js#L452

What it's doing is checking to see if you added a new service and then it shares with the server and that data looks like this:

![](http://i.imgur.com/3qHEzkZ.png)

I then approve it for everyone by clicking "approve public". If it's private I reject it unless someone requests that it should be privately approved (no one does). If those criteria fail then I hit reject. the person who installed it locally can continue to use it, but the server has no more record of it.

**Comment by Noitidart** [comment]
A screenshot of the mbam report would be nice too please if possible.

**Comment by soundfeelings** [comment]
ok. here is the screenshot. You are saying that it is not malicious code. my malware program just THINKS it is bad? 
![maliciouswebsiteblocked-mailtowebmails](https://cloud.githubusercontent.com/assets/17467206/13311291/0a837e62-db42-11e5-93ea-dc454f5bb485.JPG)

**Comment by Noitidart** [comment]
I am using a free web host for that. I bought hosting last month, I'll transition it over to the new host and see if it makes a difference.

Thanks for the screenshot.

**Comment by soundfeelings** [comment]
That is great news. Thanks for the update.

**Comment by Noitidart** [comment]
Fixed in 2.8 release, I switched to a paid server. Before I was using a free server which I think was causing the problems.
