### ISSUE TITLE
Add Webservice Request: NetEase

### ISSUE THREAD

**Issue by lunchboxer** [Noitidart/MailtoWebmails#8]
I was trying to install a webmail service from the options panel of MailtoWebesrvices but the one I was looking for was not found. I was looking for NetEase webmail, a very popular Chinese webmail service. They don't have an English version but you can find more at http://email.163.com . It's the biggest webmail service in China unless you count QQ.

**Comment by highwindmx** [comment]
I am interested and also need this one, tell me if any thing I can help.

**Comment by highwindmx** [comment]
And also, I think if a recipe function is provided would be better, 
like user can set an address which who will usually email to.

**Comment by Noitidart** [comment]
Thanks @highwindmx I am working on next release this weekend so users can add services without requesting. But to resolve this issue we have to contact this company and ask them for a wild card compose url.
